In [4]:
from pop import LiDAR, Pilot

lidar = LiDAR.Rplidar()            # LiDAR 객체 생성
car = Pilot.AutoCar()              # AutoCar 객체 생성

lidar.connect()
lidar.startMotor()

car.setSpeed(90)                    # 속도
car.steering = 0                     # 조향 가운데

while True:
    no_collision = True
    
    vectors = lidar.getVectors()
    for v in vectors:
        degree = v[0]
        distance = v[1]
        
        if degree <= 60 or degree >= 300:
            if distance <= 700:
                no_collision = False
            if no_collision:
                car.setSpeed(99)
                car.forward()
            else:
                if car.steering == 0:
                    car.stop()
                car.steering = -1
                car.backward(50)


KeyboardInterrupt: 

In [5]:
from pop import LiDAR, Pilot

lidar = LiDAR.Rplidar()            # LiDAR 객체 생성
car = Pilot.AutoCar()              # AutoCar 객체 생성

lidar.connect()

car.stop()
car.steering = 0
lidar.stopMotor()

In [ ]:

from pop import Util
Util.createIMG()

import cv2
from pop import LiDAR, Pilot

lidar = LiDAR.Rplidar()            # LiDAR 객체 생성
car = Pilot.AutoCar()              # AutoCar 객체 생성

lidar.connect()
lidar.startMotor()

image = cv2.imread("img.jpg", cv2.IMREAD_COLOR)
height, width, channel = image.shape

print("%d, %d, %d" % (width, height, channel))

In [13]:
import cv2
from pop import Util

Util.enable_imshow()

filename = "img.jpg"

imgColor = cv2.imread(filename, cv2.IMREAD_COLOR)
imgGray = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)

cv2.imshow("Color", imgColor)
cv2.imshow("GrayScale", imgGray)


Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

In [2]:
import cv2
from pop import Util

Util.enable_imshow()

imgGray = cv2.imread("img.jpg", cv2.IMREAD_COLOR)

b, g, r = cv2.split(imgOrigin)
imgNew = cv2.merge([r, g, b])

cv2.imshow("Origin", imgOrigin)
cv2.imshow("New", imgNew)

cv2.waitKey(0)
cv2.destroyAllWindows()

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

In [4]:
import cv2

imgOrigin = cv2.imread("img.jpg", cv2.IMREAD_COLOR)
imgGray = cv2.imread("img.jpg", cv2.IMREAD_GRAYSCALE)

cv2.imwrite("img.jpg", imgOrigin)
cv2.imwrite("imgGray.jpg", imgGray)

cv2.imshow("img.jpg", imgOrigin)
cv2.imshow("imgGray.jpg", imgGray)

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

In [ ]:
import cv2

cam = "nvarguscamerasrc! video/x-raw (memory:NVMM), width=(int) 640, height=(int)480, format=(string)NV12, framerate=(fraction) 30/1! nvvidconv flip-method=0! video/x-raw, width=(int)640, height=(int)480, format=(string)BGRx! videoconvert! video/x-raw, format=(string)BGR! appsink"

cv2.VideoCapture(cam, cv2.CAP_GSTREAMER)

In [65]:
import cv2
from pop import Util,Pilot

car = Pilot.AutoCar()



Util.enable_imshow()

cam = Util.gstrmer(width=640, height=480)

camera = cv2.VideoCapture(cam, cv2.CAP_GSTREAMER)
if not camera.isOpened():
    print("Not found camera")

width = camera.get(cv2.CAP_PROP_FRAME_WIDTH)
height = camera.get(cv2.CAP_PROP_FRAME_HEIGHT)
print("init width: %d, init height: %d" % (width,height))


angle_p = 3
angle_t = -20
direction_p = 3
direction_t = 3
while True:
#for _ in range(120):
    ret, frame = camera.read()
    
    if not ret:
        print("프레임 못 잡음")
        break

    car.camPan(angle_p)
    car.camTilt(angle_t)
    cv2.imshow("soda", frame)
    
    angle_p += direction_p
    angle_t += direction_t
    
    if angle_p >=180:
        direction_p = -3
    elif angle_p <= 4:
        direction_p = 3
        
    if angle_t >=90:
        direction_t = -3
    elif angle_t <= -20:
        direction_t = 3
 
    


camera.release()
cv2.destroyAllWindows()

init width: 640, init height: 480


Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

KeyboardInterrupt: 

In [41]:
import cv2
from pop import Util, Pilot

Util.enable_imshow()
car = Pilot.AutoCar()

cam = Util.gstrmer(width=640, height=480)

camera = cv2.VideoCapture(cam, cv2.CAP_GSTREAMER)
if not camera.isOpened():
    print("Not found camera")

width = camera.get(cv2.CAP_PROP_FRAME_WIDTH)
height = camera.get(cv2.CAP_PROP_FRAME_HEIGHT)
print("init width: %d, init height: %d" % (width, height))

for i in range(120):                     # for문 이용 카메라 촬영하면서 우로 이동
    ret, frame = camera.read()
    car.camPan(i)
    if not ret:                          # ret가 0이 아니면 코드를 실행
        break

    cv2.imshow("soda", frame)

for i in range(120):                     # for문 이용 카메라 촬영하면서 좌로 이동
    ret, frame = camera.read()
    car.camPan(119 - i)
    if not ret:
        break

    cv2.imshow("soda", frame)

camera.release()
cv2.destroyAllWindows()

init width: 640, init height: 480


Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

In [42]:
import cv2
from pop import Util

Util.enable_imshow()

cam=Util.gstrmer(width=640, height=480)
camera=cv2.VideoCapture(cam, cv2.CAP_GSTREAMER)
if not camera.isOpened():
    print("Not found camera")
    
fourcc = cv2.VideoWriter_fourcc(*"X264")
out = cv2.VideoWriter("soda.avi", fourcc, 30, (640,480))

for _ in range(120):
    ret, frame = camera.read()
    framGray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    out.write(frame)
    
    cv2.imshow("soda", framGray)
    
camera.release()
cv2.destroyAllWindows()

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

In [71]:
import cv2
from pop import Util

Util.enable_imshow()

cam = Util.gstrmer(width=640, height=480)
camera = cv2.VideoCapture(cam, cv2.CAP_GSTREAMER)
if not camera.isOpened():
    print("NOT found camera")
    
for _ in range(120):
    ret, frame = camera.read()
    img = cv2.Canny(frame, 100, 200)
    
    cv2.imshow("soda", img)
    
camera.release()
cv2.destroyAllWindows()

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

In [3]:
import cv2
from pop import Util

Util.enable_imshow()

haar_face='/usr/local/share/opencv4/haarcascades/haarcascade_frontalface_default.xml'
face_cascade = cv2.CascadeClassifier(haar_face)

cam = Util.gstrmer(width=640, height=480)
camera = cv2.VideoCapture(cam, cv2.CAP_GSTREAMER)
if not camera.isOpened():
    print("NOT found camera")
    
for _ in range(300):
    ret, frame = camera.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, scaleFactor = 1.3, minNeighbors = 1, minSize = (100, 100))
    
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0 , 0), 2)
    cv2.imshow('img', frame)
        
camera.release()
cv2.destroyAllWindows()

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

In [23]:
import pyaudio
import wave

w = wave.open("/usr/share/sounds/alsa/Front_Center.wav", "rb")
data = w.readframes(w.getnframes())

p = pyaudio.PyAudio()
stream = p.open(format = p.get_format_from_width(2),
               channels = 1,
               rate = 48000,
               output = True)

stream.write(data)

stream.stop_stream()
stream.close()

stream = p.open(format = p.get_format_from_width(w.getsampwidth()),
          channels = w.getnchannels(),
          rate = w.getframerate(),
          output = True)

w.rewind()

data = w.readframes(1024)
while len(data) > 0:
    stream.write(data)
    data = w.readframes(1024)
    
w.close()
stream.close()
p.terminate()

In [12]:
import pyaudio
import wave
import time

def callback(in_data, frame_count, time_info, status):
    data = w.readframes(frame_count)
    return (data, pyaudio.paContinue)

w = wave.open("/usr/share/sounds/alsa/Side_Left.wav", "rb")
p = pyaudio.PyAudio()

stream = p.open(format = p.get_format_from_width(w.getsampwidth()),
          channels = w.getnchannels(),
          rate = w.getframerate(),
          output = True,
          stream_callback = callback)

stream.start_stream()

while stream.is_active:
    print("main work...")
    time.sleep(0.1)
    
stream.stop_stream()
stream.close()
p.terminate()

KeyboardInterrupt: 

In [52]:
import pyaudio
import numpy as np

volume = 0.5
fs = 48000
duration = 1.0
f = 440.0

data = (np.sin(2 * np.pi * np.arange(fs * duration) * f / fs)).astype(np.float32)

p = pyaudio.PyAudio()
stream = p.open(format = pyaudio.paFloat32, channels = 1, rate = fs, output = True)
stream.write(volume * data)

stream.stop_stream()
stream.close()
p.terminate()

In [ ]:
import pyaudio
import numpy as np

class Tone:
    def __init__(self, volume = .5, rate = 48000, channels = 1):
        self.volume = volume    # self.volume : 멤버 변수    volume : 매개변수
        self.rate = rate
        self.channels = channels
        self.p = pyaudio.PyAudio()
        self.stream = self.p.open(format = pyaudio.paFloat32, channels = self.channels, rate = self.rate, output = True)
        
    def __enter__(self):
        return self
        
    def __exit__(self, type, value, traceback):
        self.stop()
            
    def stop(self):
        self.stream.stop_stream()
        self.stream.close()
        self.p.terminate()
            
    def play(self, octave, note, duration):
        f = 2 ** (octave) * 55 * 2 ** (((note) - 10) / 12)
        sample = (np.sin(2 * np.pi * np.arange(self.rate * duration) * f / self.rate)).astype(np.float32)
        self.stream.write(self.volume * sample)
            
with Tone() as tone:
    for n in [1, 3, 5, 6, 8, 10, 12, 131]:
        tone.play(3, n, 4)

In [ ]:
# import pyaudio
import numpy as np

class Tone:
    def __init__(self, volume = .5, rate = 48000, channels = 1):
        self.volume = volume    # self.volume : 멤버 변수    volume : 매개변수
        self.rate = rate
        self.channels = channels
        self.p = pyaudio.PyAudio()
        self.stream = self.p.open(format = pyaudio.paFloat32, channels = self.channels, rate = self.rate, output = True)
        
    def __enter__(self):
        return self
        
    def __exit__(self, type, value, traceback):
        self.stop()
            
    def stop(self):
        self.stream.stop_stream()
        self.stream.close()
        self.p.terminate()
            
    def play(self, octave, note, duration):
        f = 2 ** (octave) * 55 * 2 ** (((note) - 10) / 12)
        sample = (np.sin(2 * np.pi * np.arange(self.rate * duration) * f / self.rate)).astype(np.float32)
        self.stream.write(self.volume * sample)
            
with Tone() as tone:
#     for n in [1, 3, 5, 6, 8, 10, 12]:
#         tone.play(3, n, 4)
    tone = input("1, 3, 5, 6, 8, 10, 12 중 하나 입력 : ")
    if tone == 1:
        tone.play(1)

In [ ]:
import numpy as np
from pop import Cds, delay
from pop import Pilot

car = Pilot.AutoCar()
cds = Cds(7)

while True:
    value = cds.readAverage()
    print(value)
    if value >= 700:
        car.forward(99)
    if value < 700:
        car.forward(20)
    if value < 50:
        car.stop()
        break
    delay(500)

In [ ]:
import numpy as np
from pop import Cds, delay
from pop import Pilot

car = Pilot.AutoCar()
cds = Cds(7)

while True:
    value = cds.readAverage()
    print(value)
    car.forward(value/16)
    if value < 50:
        car.stop()
    delay(500)

In [48]:
import pandas as pd  # pandas 라이브러리를 pd라는 이름으로 임포트

# 데이터와 인덱스를 정의
value = [32, 68, 220, 77]  # 값 리스트
index = ["온도", "습도", "강수량", "불쾌지수"]  # 각 값의 인덱스

# Series 객체 생성
sr = pd.Series(value, index=index)  # value와 index를 사용하여 Series 생성

# Series의 타입과 내용을 출력
print(type(sr))  # sr의 타입 출력
print(sr)  # sr의 내용을 출력
print(sr.index)  # sr의 인덱스 출력
print(sr.values)  # sr의 값 출력

print(sr.iloc[0])        # iloc 행번호로 출력
print(sr.loc['습도'])    # loc 인덱스로 출력
print(sr.iloc[-1])

<class 'pandas.core.series.Series'>
온도       32
습도       68
강수량     220
불쾌지수     77
dtype: int64
Index(['온도', '습도', '강수량', '불쾌지수'], dtype='object')
[ 32  68 220  77]
32
68
77


In [49]:
print(sr)

온도       32
습도       68
강수량     220
불쾌지수     77
dtype: int64


In [51]:
sr.loc['좋음'] = 0    # 추가

In [52]:
sr2 = sr.drop('좋음')
print(sr)                # series의 원본에는 삭제가 되지 않는다
print(sr2)                # 삭제된 새로운 series

온도       32
습도       68
강수량     220
불쾌지수     77
좋음        0
dtype: int64
온도       32
습도       68
강수량     220
불쾌지수     77
dtype: int64


In [53]:
sr = sr.drop("불쾌지수")
print(sr)

온도      32
습도      68
강수량    220
좋음       0
dtype: int64


In [54]:
data = [19, 14, 12]
index = ['하나', '둘', '셋']
s = pd.Series(data, index)
print(s)

s['둘'] = 22                    # 인덱스
print(s)                        
s.loc['하나'] = 1
print(s)

하나    19
둘     14
셋     12
dtype: int64
하나    19
둘     22
셋     12
dtype: int64
하나     1
둘     22
셋     12
dtype: int64


In [55]:
from pandas import Series
s = Series([10, 20, 30])
print(s)

print(s + 5)

0    10
1    20
2    30
dtype: int64
0    15
1    25
2    35
dtype: int64


In [57]:
h = Series([10, 20, 30, 40, 50])
l = Series([1, 2, 3, 4, 5])
diff = (h - l)
print(diff)

0     9
1    18
2    27
3    36
4    45
dtype: int64


In [58]:
cond = diff > 30
print(cond)

0    False
1    False
2    False
3     True
4     True
dtype: bool


In [65]:
# 고가와 저가의 차이가 100 이상인 고가를 출력하시오
저가 = pd.Series([10, 200, 200, 400, 600])
고가 = pd.Series([100, 300, 400, 500, 600])

cond = (고가 - 저가) >= 100
print(cond)

고가[cond]

0    False
1     True
2     True
3     True
4    False
dtype: bool


1    300
2    400
3    500
dtype: int64

In [89]:
# 종가가 8만원 이상이고 90000원 미만의 요일을 출력하시오
data = [80010, 87100,77800, 99000, 79900]
요일 = ['월', '화', '수', '목', '금']


종가 = pd.Series(data, 요일)
종가

조건 = (80000 <= 종가) & (종가 < 90000)
조건

종가[조건].index

Index(['월', '화'], dtype='object')

In [92]:
import numpy as np

x = np.arange(4).reshape(2, 2)
print(x)

y = np.arange(3, -1, -1).reshape(2, 2)
print(y)

s1 = np.matmul(x, y)
print(s1)

[[0 1]
 [2 3]]
[[3 2]
 [1 0]]
[[1 0]
 [9 4]]


In [99]:
x = np.arange(4).reshape(2, 2)
print(x)

s1 = np.abs(x)      # 절댓값
print(s1)
s2 = np.square(x)   # 제곱
print(s2)
s3 = np.sqrt(x)     # 제곱근
print(s3)
s4 = np.log(x)      # 로그
print(s4)

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[0 1]
 [4 9]]
[[0.         1.        ]
 [1.41421356 1.73205081]]
[[      -inf 0.        ]
 [0.69314718 1.09861229]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in log
  # Remove the CWD from sys.path while we load stuff.


In [100]:
x = np.arange(4).reshape(2, 2)
print(x)

y = np.arange(3, -1, -1).reshape(2, 2)
print(y)

s1 = np.where(x > y, x, y)
print(s1)

[[0 1]
 [2 3]]
[[3 2]
 [1 0]]
[[3 2]
 [2 3]]


In [101]:
import pandas as pd

values = [[32, 68, 220, 72], [20, 30, 0, 12], [38, 81, 0, 91]]               # 3 X 4 2차원
df = pd.DataFrame(values)
print(df)

    0   1    2   3
0  32  68  220  72
1  20  30    0  12
2  38  81    0  91


In [102]:
df[0][1]

20

In [104]:
list = [[32, 68, 220, 72], [20, 30, 0, 12], [38, 81, 0, 91]]
print(list[0][1])

68


In [105]:
import pandas as pd

values = [[32, 68, 220, 72], [20, 30, 0, 12], [38, 81, 0, 91]]

columns = ['온도', '습도', '강수량', '불쾌지수']
index = ['초여름', '늦봄', '한여름']
df = pd.DataFrame(values, index, columns)
print(df)

     온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12
한여름  38  81    0    91


In [106]:
print(df['온도'])

초여름    32
늦봄     20
한여름    38
Name: 온도, dtype: int64


In [108]:
print(df['온도']['늦봄'])

20


In [127]:
print(df.loc['늦봄'])    # loc: 인덱스, Series
print(df.iloc[[1]])        # iloc: 행 번호

    온도  습도  강수량  불쾌지수
늦봄  20  30    0    12
    온도  습도  강수량  불쾌지수
늦봄  20  30    0    12


In [122]:
values = [[32, 68, 220, 72], [20, 30, 0, 12], [38, 81, 0, 91]]

columns = ['온도', '습도', '강수량', '불쾌지수']
index = ['초여름', '늦봄', '한여름']
df = pd.DataFrame(values, index, colums)

print(df)
print(df.index)
print(df.columns)
print(df.values)

     온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12
한여름  38  81    0    91
Index(['초여름', '늦봄', '한여름'], dtype='object')
Index(['온도', '습도', '강수량', '불쾌지수'], dtype='object')
[[ 32  68 220  72]
 [ 20  30   0  12]
 [ 38  81   0  91]]


In [125]:
print(df[['온도', '강수량']])

     온도  강수량
초여름  32  220
늦봄   20    0
한여름  38    0


In [128]:
df.iloc[[0, 1]]

온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12

In [138]:
print(df.iloc[[0, 1]])
print(df.loc[['초여름', '늦봄']])

     온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12
     온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12


In [131]:
df.loc[['초여름', '늦봄']]

온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12

In [139]:
df.iloc[0:2]

온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12

In [141]:
df.loc['초여름':'늦봄']

온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12

In [158]:
df

온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12
한여름  38  81    0    91

In [148]:
print(df.loc['초여름', '온도'])    # 인덱스: 행 X 열
print(df.loc[:, '온도'])
print(df.loc[:, '습도':'강수량'])

32
초여름    32
늦봄     20
한여름    38
Name: 온도, dtype: int64
     온도  습도  강수량
초여름  32  68  220
늦봄   20  30    0
한여름  38  81    0


In [160]:
조건 = df['온도'] >= 30
print(df[조건])

     온도  습도  강수량  불쾌지수
초여름  32  68  220    72
한여름  38  81    0    91
